listener: 
    # host and port of the mongodb used to store scheduled jobs
    mongo_host: 127.0.0.1
    mongo_port: 27017

    # name of the mongodb database to store eventbus related data
    mongo_db: eventbus

    # collection that stores the jobs to be triggered by events 
    mongo_job_collection: jobs

    # interval in seconds in which to poll the mongodb for job definitions 
    mongo_poll_interval: 20

    amq_host: 
    amq_port:

    publish_queue_name: /topic/agent
    subscribe_queue_name: /queue/listener
     
agent:
    mongo_host: localhost
    mongo_port: 27017
    mongo_db: local
    mongo_oplog_collection: oplog.rs

    # in seconds
    mongo_connection_retry: 5

    mongo_ignore_initial_read: true

    # in seconds
    throttle_polling_period: 5

    start_heartbeat: true
    start_node_detector: false

    publish_queue_name: /queue/listener
    subscribe_queue_name: /topic/agent

    messaging_host: devparallax.slidev.org
