# logging configuration 
logger_output: STDOUT
logger_level: WARN

# set the node-id that is prefixed to the hostname 
node_id: oplogagent-1-

# url of ActiveMQ running STOMP protocol used as message broker
broker_url: stomp://localhost:61613

# the interval in which to send a heartbeat in seconds 
heartbeat_period: 10

# MongoDB configuration 
# host and port of the mongoDB installation that the oplog agent 
# should connect to 
mongo_host: localhost:10001, localhost:10002, localhost:10003
#mongo_port: 10001

# database and collection that the oplog agent should follow 
mongo_db: local
mongo_oplog_collection: oplog.rs

# parameters for the connection to mongo in seconds
mongo_connection_retry: 5
mongo_ignore_initial_read: true

# time frame in which to coalesce oplog messages in seconds
# all messages within this timeframe will be processed together and generate 
# a single event 
collect_events_interval: 5
