common: &common
    recaptcha_disable: true
    terms_url: http://dev.slcedu.org/legal/terms-service
    privacy_policy_url: http://dev.slcedu.org/legal/privacy
    # TODO:  change these keys.  Use a to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
    # update me when password policy changes
    password_policy: ["password must satisfy password policy"]
    support_email: support@slidev.org
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    admin_realm: Shared Learning Infrastructure

sandbox: &sandbox
    is_sandbox: true
    maximum_user_count: 500

ldap_default: &ldap_default
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{

email_mon: &email_mon
    email_sender_name: SLC Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000

email_rumbster: &email_rumbster
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: 127.0.0.1
    email_port: 2525

development:
    <<: *common
    <<: *email_mon
    <<: *ldap_default
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    is_sandbox: false
    email_replace_uri: http://local.slidev.org:3000
    portal_url: https://rcportal.slidev.org/portal
    
local-acceptance-tests:
    <<: *common
    <<: *email_rumbster
    <<: *ldap_default
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    is_sandbox: false
    email_replace_uri: http://local.slidev.org:2000
    portal_url: https://rcportal.slidev.org/portal
    
development_sb:
    <<: *common
    <<: *sandbox
    <<: *email_mon
    <<: *ldap_default
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    email_replace_uri: http://local.slidev.org:3000
    portal_url: https://rc2portal.slidev.org/portal
    sample_data_url: http://www.slcedu.org
    
team:
    <<: *common
    <<: *email_mon
    <<: *ldap_default
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: false
    portal_url: https://rcportal.slidev.org/portal
    
team_sb:
    <<: *common
    <<: *sandbox
    <<: *email_mon
    <<: *ldap_default
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    email_replace_uri: https://ci.slidev.org:2001
    portal_url: https://rc2portal.slidev.org/portal
    sample_data_url: http://www.slcedu.org
    
test:
    <<: *common
    <<: *email_mon
    <<: *ldap_default
    api_base: https://devapp1.slidev.org/api/rest
    ldap_base: ou=DevTest,dc=slidev,dc=org
    is_sandbox: false
    email_replace_uri: http://local.slidev.org:3000
    portal_url: https://rcportal.slidev.org/portal
    
production:
    <<: *common
    <<: *email_mon
    <<: *ldap_default
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: false
    portal_url: https://rcportal.slidev.org/portal
