development:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:3000
    admin_realm: Shared Learning Infrastructure
local-acceptance-tests:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:2000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:2000
    admin_realm: Shared Learning Infrastructure    
development_sb:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: true
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:3000
    admin_realm: Shared Learning Infrastructure
team:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=ciTest,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: false
    admin_realm: Shared Learning Infrastructure
team_sb:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=ciTest,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: true
    admin_realm: Shared Learning Infrastructure
test:
    api_base: https://devapp1.slidev.org/api/rest
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 3000
    admin_realm: Shared Learning Infrastructure
