development:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:3000
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rcportal.slidev.org/portal
    recaptcha_disable: true
# TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
local-acceptance-tests:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: 127.0.0.1
    email_port: 2525
    email_replace_uri: http://local.slidev.org:2000
    admin_realm: Shared Learning Infrastructure  
    redirect_slc_url: http://www.slcedu.org  
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rcportal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
development_sb:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=Local,ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: true
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:3000
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rc2portal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
team:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: false
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rcportal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
team_sb:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: true
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rc2portal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
test:
    api_base: https://devapp1.slidev.org/api/rest
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: http://local.slidev.org:3000
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org    
    support_email: support@slidev.org
    portal_url: https://rcportal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
production:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=SLIAdmin,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_sender_name: SLI Administrator
    email_sender_address: ufhalhffhuwhelfjkdfhs@slidev.org
    email_host: mon.slidev.org
    email_port: 3000
    email_replace_uri: https://ci.slidev.org:2001
    is_sandbox: false
    admin_realm: Shared Learning Infrastructure
    redirect_slc_url: http://www.slcedu.org
    email_sender_name_user_reg_app: Administrator
    email_sender_address_user_reg_app: noreply@slidev.org
    support_email: support@slidev.org
    portal_url: https://rcportal.slidev.org/portal
    recaptcha_disable: true
    # TODO: use some to-be-designated WGen account to create the recaptcha API keys.  The ones below are created with my rfarris@wgen.net account.
    recaptcha_pub: 6LcKNNISAAAAABcaWTbWUFsmAGiIr97Gw7xOj4hs
    recaptcha_priv: 6LcKNNISAAAAANwi1R1BY6SxJrYVv8oMimQ69Hfs
