development:
    api_base: http://local.slidev.org:8080/api/rest
    client_id: Eg6eseKRzN
    client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    redirect_uri: http://local.slidev.org:3000/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 25
test:
    api_base: https://devapp1.slidev.org/api/rest
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 25
deployment:
    api_base: https://nxbuild.slidev.org/api/rest
    client_id: BsgPgjFApl
    client_secret: 5Upgg8a5bfX5nA121IIFMDCGVAF6NtH2nAIch0BinjUAWtiH
    redirect_uri: https://devadmin1.slidev.org/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    is_sandbox: false
    email_host: mon.slidev.org
    email_port: 25
integration:
    api_base: https://testapi1.slidev.org/api/rest
    client_id: zl9FejUhnV
    client_secret: V80Ah5GpjZvA7hNLxWmZ6Hy5mE4tEuSb5z0Re9AXNUkAMVyp
    redirect_uri: https://testadmin1.slidev.org/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
acceptance-tests:
    api_base: https://nxbuild.slidev.org/api/rest
    client_id: zl9FejUhnV
    client_secret: V80Ah5GpjZvA7hNLxWmZ6Hy5mE4tEuSb5z0Re9AXNUkAMVyp
    redirect_uri: https://nxbuild.slidev.org/admin/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_host: mon.slidev.org
    email_port: 25
nxbuild2:
    api_base: https://nxbuild2.slidev.org/api/rest
    client_id: zl9FejUhnV
    client_secret: V80Ah5GpjZvA7hNLxWmZ6Hy5mE4tEuSb5z0Re9AXNUkAMVyp
    redirect_uri: https://nxbuild2.slidev.org/admin/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
team:
    api_base: https://ci.slidev.org/api/rest
    client_id: OY6Nnukmn6
    client_secret: UxeLZVB6rM1hBL3ZEpRSkGvfdkMTTUgJH77UyTCU462zXNIg
    redirect_uri: https://ci.slidev.org:2001/callback
    ldap_host: ldap.slidev.org
    ldap_port: 389
    ldap_base: ou=DevTest,dc=slidev,dc=org
    ldap_user: cn=DevLDAP User, ou=People,dc=slidev,dc=org
    ldap_pass: Y;Gtf@w{
    email_host: mon.slidev.org
    email_port: 25
    

