development:
#    api_base: https://devapp1.slidev.org/api/rest
    api_base: http://local.slidev.org:8080/api/rest
    client_id: 2zhRrEXh8r
    client_secret: uOoKXLWihlz39EEQ7Uoqqc7TeogsnQnDAUs3HWYFouZFG5sk
    redirect_uri: http://local.slidev.org:3000/callback
test:
    api_base: https://devapp1.slidev.org/api/rest
deployment:
    api_base: https://devapp1.slidev.org/api/rest
    client_id: kW1yIK2cMn
    client_secret: B5Y20Qi9Hp1ds5lMxWG9PiELwKRyb4xNgdh6Jm8G0my1lPHA
    redirect_uri: https://devdatab1.slidev.org/callback
integration:
    api_base: https://testapi1.slidev.org/api/rest
    client_id: pAKLACLtzV
    client_secret: WqfVf4mU3oepkED6NXDn1oyWUDOG6fpBL8Or55gSfhNrhq2K
    redirect_uri: https://testdatab1.slidev.org/callback
